from pathlib import Path

current_dir = Path.cwd()
project_root = current_dir.parent.parent.parent
data_root = str(project_root / "src" / "datasets" / "etts" / "data")

etth1_config_lmu  = {
    "data_root": data_root,
    "batch": 64,
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTh1",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    "epochs": 50,
    "lr": 2e-4,
    "wd": 1e-3,
    "amp": True,
    "save_dir": "./runs/etts_lmu_task_etth1",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 6,
    "dropout": 0.5 ,# -> 0.2,
    "mlp_ratio": 2.0,
    "droppath_final": 0.2, # -> 0.1,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
}

etth2_config_lmu = {
    "data_root": data_root,
    "batch": 64,
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTh2",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_lmu_task_etth2",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.55,
    "mlp_ratio": 2.0,
    "droppath_final": 0.3,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
}

ettm1_config_lmu = {
    "data_root": data_root,
    "batch": 64,
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTm1",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_lmu_task_ettm1",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.55,
    "mlp_ratio": 2.0,
    "droppath_final": 0.3,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
}

ettm2_config_lmu = {
    "data_root": data_root,
    "batch": 64,
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTm2",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_lmu_task_ettm2",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.55,
    "mlp_ratio": 2.0,
    "droppath_final": 0.3,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
}

s4_base_params = {
    "d_state": 64,
    "channels": 1,
    "bidirectional": False,
    "mode": "s4d",
    "dt_min": 1e-3,
    "dt_max": 1e-1,
}

etth1_config_s4 = {
    "data_root": data_root,
    "batch": 64,
    "epochs": 50,
    "lr": 1e-4,
    "wd": 1e-3,
    "amp": True,
    "save_dir": "./runs/etts_s4_task_etth1",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 6,
    "dropout": 0.3,
    "mlp_ratio": 2.0,
    "droppath_final": 0.1,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTh1",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    **s4_base_params
}

etth2_config_s4 = {
    "data_root": data_root,
    "batch": 64,
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_s4_task_etth2",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.3,
    "mlp_ratio": 2.0,
    "droppath_final": 0.1,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTh2",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    **s4_base_params
}

ettm1_config_s4 = {
    "data_root": data_root,
    "batch": 64,
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_s4_task_ettm1",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.3,
    "mlp_ratio": 2.0,
    "droppath_final": 0.1,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTm1",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    **s4_base_params
}

ettm2_config_s4 = {
    "data_root": data_root,
    "batch": 64,
    "epochs": 50,
    "lr": 1e-4,
    "wd": 2e-3,
    "amp": True,
    "save_dir": "./runs/etts_s4_task_ettm2",
    "warmup_epochs": 5,
    "patience": 10,
    "min_delta": 0.001,
    "d_model": 256,
    "depth": 4,
    "dropout": 0.3,
    "mlp_ratio": 2.0,
    "droppath_final": 0.1,
    "layerscale_init": 1e-2,
    "residual_gain": 1.0,
    "pool": "none",
    "data_loader_kwargs": {
        "num_workers": 0,
        "which": "ETTm2",
        "seq_len": 96,
        "pred_len": 24,
        "feature_mode": "target",
        "target_col": "OT",
        "split_ratio": (0.7, 0.1, 0.2),
        "normalize": "zscore",
        "pin_memory": False,
        "persistent_workers": False,
    },
    **s4_base_params
}
